### PR TITLE
Test: trng: Add CMake file

### PR DESCRIPTION
**Pull request by pfalcon**
Signed-off-by: Paul Sokolovsky <paul.sokolovsky@linaro.org>

### CODE REVIEW

**Comment by pfalcon** [comment]
Intended to work with https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/19 .

This PR doesn't include  MCU-Driver-HAL submodule update, as I'm not sure what's the right approach to do that yet.

**Comment by pfalcon** [comment]
Test output:
```
$ mbedhtrun -f ./sdfx_st/tests/mbed_hal/trng/cmake_build/sdfx-st-test-trng.bin -e MCU-Driver-HAL/tests/host_tests/ -d /media/pfalcon/DIS_L4IOT/ -p /dev/ttyACM0:115200
[1625664939.16][HTST][INF] host test executor ver. 1.4.4
[1625664939.16][HTST][INF] copy image onto target...
[1625664944.96][MBED][WRN] Target ID not found: Skipping flash check and retry
[1625664944.97][HTST][INF] starting host test process...
[1625664944.97][CONN][INF] starting connection process...
[1625664944.97][CONN][INF] notify event queue about extra 60 sec timeout for serial port pooling
[1625664944.97][CONN][INF] initializing serial port listener... 
[1625664944.97][SERI][INF] serial(port=/dev/ttyACM0, baudrate=115200, read_timeout=0.01, write_timeout=5)
[1625664944.97][HTST][INF] setting timeout to: 60 sec
[1625664944.97][SERI][INF] reset device using 'default' plugin...
[1625664945.08][SERI][INF] waiting 1.00 sec after reset
[1625664946.08][SERI][INF] wait for it...
[1625664946.08][SERI][TXD] mbedmbedmbedmbedmbedmbedmbedmbedmbedmbed
[1625664946.08][CONN][INF] sending up to 2 __sync packets (specified with --sync=2)
[1625664946.08][CONN][INF] sending preamble '44404f33-d139-4bdb-9aa5-83a09cd17f11'
[1625664946.08][SERI][TXD] {{__sync;44404f33-d139-4bdb-9aa5-83a09cd17f11}}
[1625664946.10][CONN][RXD] mbedmbedmbedmbedmbedmbedmbedmbed
[1625664946.11][CONN][INF] found SYNC in stream: {{__sync;44404f33-d139-4bdb-9aa5-83a09cd17f11}} it is #0 sent, queued...
[1625664946.11][CONN][INF] found KV pair in stream: {{__version;1.3.0}}, queued...
[1625664946.11][CONN][INF] found KV pair in stream: {{__timeout;100}}, queued...
[1625664946.11][CONN][INF] found KV pair in stream: {{__host_test_name;trng_reset}}, queued...
[1625664946.11][CONN][INF] found KV pair in stream: {{__testcase_count;1}}, queued...
[1625664946.11][HTST][INF] sync KV found, uuid=44404f33-d139-4bdb-9aa5-83a09cd17f11, timestamp=1625664946.106323
[1625664946.11][HTST][INF] DUT greentea-client version: 1.3.0
[1625664946.11][HTST][INF] setting timeout to: 100 sec
[1625664946.11][HTST][INF] host test class: '<class 'trng_reset.TRNGResetTest'>'
[1625664946.11][HTST][INF] host test setup() call...
[1625664946.11][HTST][INF] CALLBACKs updated
[1625664946.11][HTST][INF] host test detected: trng_reset
[1625664946.12][CONN][RXD] >>> Running 1 test cases...
[1625664946.12][CONN][RXD] 
[1625664946.12][CONN][RXD] >>> Running case #1: 'TRNG: trng_test'...
[1625664946.12][CONN][INF] found KV pair in stream: {{__testcase_name;TRNG: trng_test}}, queued...
[1625664946.12][CONN][INF] found KV pair in stream: {{__testcase_start;TRNG: trng_test}}, queued...
[1625664946.13][CONN][INF] found KV pair in stream: {{ready;0}}, queued...
[1625664946.14][SERI][TXD] {{check_step1;0}}
[1625664946.15][CONN][INF] found KV pair in stream: {{buffer;5f/9TowlQ2qgsS67YTcK3CtFRb7Ia5FgNPktoNANSxw=}}, queued...
[1625664946.16][CONN][INF] received special event '__reset', resetting dut
[1625664946.16][SERI][INF] reset device using 'default' plugin...
[1625664946.27][SERI][INF] waiting 1.00 sec after reset
[1625664947.27][SERI][INF] wait for it...
[1625664947.28][SERI][TXD] {{__sync;0}}
[1625664947.29][CONN][RXD] mbedmbedmbedmbedmbedmbedmbedmbed
[1625664947.29][CONN][INF] found KV pair in stream: {{__sync;0}}, queued...
[1625664947.29][CONN][INF] found KV pair in stream: {{__version;1.3.0}}, queued...
[1625664947.29][HTST][ERR] orphan event in main phase: {{__sync;0}}, timestamp=1625664947.291720
[1625664947.29][CONN][INF] found KV pair in stream: {{__timeout;100}}, queued...
[1625664947.29][HTST][ERR] orphan event in main phase: {{__version;1.3.0}}, timestamp=1625664947.291738
[1625664947.29][HTST][ERR] orphan event in main phase: {{__timeout;100}}, timestamp=1625664947.291752
[1625664947.30][CONN][RXD] >>> Running 1 test cases...
[1625664947.30][CONN][RXD] 
[1625664947.30][CONN][INF] found KV pair in stream: {{__host_test_name;trng_reset}}, queued...
[1625664947.30][CONN][INF] found KV pair in stream: {{__testcase_count;1}}, queued...
[1625664947.30][CONN][INF] found KV pair in stream: {{__testcase_name;TRNG: trng_test}}, queued...
[1625664947.31][HTST][ERR] orphan event in main phase: {{__host_test_name;trng_reset}}, timestamp=1625664947.303431
[1625664947.32][CONN][RXD] >>> Running case #1: 'TRNG: trng_test'...
[1625664947.32][CONN][INF] found KV pair in stream: {{__testcase_start;TRNG: trng_test}}, queued...
[1625664947.32][CONN][INF] found KV pair in stream: {{ready;0}}, queued...
[1625664947.33][SERI][TXD] {{check_step2;5f/9TowlQ2qgsS67YTcK3CtFRb7Ia5FgNPktoNANSxw=}}
[1625664947.34][CONN][INF] found KV pair in stream: {{Test_suite_ended;0}}, queued...
[1625664947.35][SERI][TXD] {{exit;0}}
[1625664947.36][CONN][RXD] >>> 'TRNG: trng_test': 1 passed, 0 failed
[1625664947.36][CONN][RXD] 
[1625664947.36][CONN][INF] found KV pair in stream: {{__testcase_finish;TRNG: trng_test;1;0}}, queued...
[1625664947.37][CONN][RXD] >>> Test cases: 1 passed, 0 failed
[1625664947.37][CONN][INF] found KV pair in stream: {{__testcase_summary;1;0}}, queued...
[1625664947.37][CONN][INF] found KV pair in stream: {{end;success}}, queued...
[1625664947.37][CONN][INF] found KV pair in stream: {{__exit;0}}, queued...
[1625664947.37][HTST][INF] __exit(0)
[1625664947.37][HTST][INF] __notify_complete(True)
[1625664947.37][HTST][INF] __exit_event_queue received
[1625664947.37][HTST][INF] test suite run finished after 1.26 sec...
[1625664947.38][CONN][INF] received special event '__host_test_finished' value='True', finishing
[1625664947.38][HTST][INF] CONN exited with code: 0
[1625664947.39][HTST][INF] Some events in queue
[1625664947.39][HTST][INF] stopped consuming events
[1625664947.39][HTST][INF] host test result() call skipped, received: True
[1625664947.39][HTST][INF] calling blocking teardown()
[1625664947.39][HTST][INF] teardown() finished
[1625664947.39][HTST][INF] {{result;success}}
```

**Comment by MarceloSalazar** [comment]
> This PR doesn't include MCU-Driver-HAL submodule update, as I'm not sure what's the right approach to do that yet.

The submodule should be updated once https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/19 is merged

We'll be adding details about this in the contribution/testing process.

**Comment by pfalcon** [comment]
Added commit to update MCU-Driver-HAL submodule.

**Review by fkjagodzinski — DISMISSED** [review]

**Comment by MarceloSalazar** [comment]
@pfalcon please rebase and resolve conflicts - we'll review again and merge shortly after this

**Comment by pfalcon** [comment]
@MarceloSalazar

> please rebase and resolve conflicts - we'll review again and merge shortly after this


Done

**Review by MarceloSalazar — APPROVED** [review]

**Pull request merged**
