### PR TITLE
Add license file

### PR DESCRIPTION
**Pull request by evedon**

### CODE REVIEW

**Review by galak — CHANGES_REQUESTED** [review]
Can the LICENSE file match what is here https://www.apache.org/licenses/LICENSE-2.0.txt  (main issue is formatting).

**Comment by MarceloSalazar** [comment]
Related to this https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/4

**Comment by galak** [comment]
Most projects I've seen just have the main license in LICENSE.  I'm not sure I've seen any do LICENSE-apache-2.0.txt before.

**Comment by evedon** [comment]
I agree with @0xc0170 comment https://github.com/MCU-Driver-HAL/MCU-Driver-HAL/pull/4#discussion_r657907326 that `LICENSE-<name>` allows for multiple licenses. I'd suggest that we adopt the same scheme for this project

**Comment by 0xc0170** [comment]
> Most projects I've seen just have the main license in LICENSE. I'm not sure I've seen any do LICENSE-apache-2.0.txt before.

Correct,  my assumption was also the same. We realized the problem will be with multiple licenses in one repository. One good example is Mbed OS where we have dozen of libraries with different licenses. We agreed on having LICENSE to list all licenses in the repository (the first paragraph in the file describes it): https://github.com/ARMmbed/mbed-os/blob/master/LICENSE.md. 

Question now is what to do with repository when we have one license only? Github by default adds LICENSE file if you mark it to add a license and choose one from their list.  This is the most common use case as stated. We actually did not enforce always and kept it more relaxed so we got repos with only LICENSE text. I assume this is becase we updated our license guide late when we had already hundreds of repos. Something we can avoid this time when we are just starting.

My suggestion would be to keep licenses consistent (for one/multiple licenses in repositories):
- LICENSE file should list all licenses within a repository. LICENSE should be in a root always. Even if LICENSE contains just "Apache 2.0", it should be good as long as it's there
- `LICENSE-<spdx-id>.txt` be placed in a libraries root (in case of multiple licenses, the major license should be in the root of the repository, the other libraries have separate full license text in respective folders)
- Our license guide will provide default text for both of these files, so people can fetch it and reuse but the content of LICENSE is more relaxed as long as all licenses are provided

We could keep the first more relaxed and allow: if it's just one license in a repository, provide the full text in LICENSE. 
I am more inclined for consistency and users should consider multiple license case always (we have a good example in HAL PR referenced earlier. We almost missed that unity contains different license).

**Comment by evedon** [comment]
@galak Can we proceed with this PR?

**Review by galak — APPROVED** [review]

**Pull request merged**
