### PR TITLE
Remove Ninja from `build_all.sh` and enable parallel build in cmake

### PR DESCRIPTION
**Pull request by ithinuel**

### CODE REVIEW

**Comment by MarceloSalazar** [comment]
@jamesbeyond please review as (I assume) this configuration will be used by CI/GHA

**Comment by jamesbeyond** [comment]
Do we have to use parallel by default? I can't think of any immediate impact on the CI. 
In the long term, if the building workload is huge, this may or may not add more pressure to the CI system performance bandwidth.

**Comment by ithinuel** [comment]
For what it's worth, Ninja builds in parallel by default anyway. This PR makes it slightly more portable to other build tools by letting cmake handle it.

**Review by jamesbeyond — APPROVED** [review]

**Comment by jamesbeyond** [comment]
Do you need to update README as well?
https://github.com/MCU-Driver-HAL/MCU-Driver-ST/tree/main/sdfx_st/examples#readme

**Review by MarceloSalazar — APPROVED** [review]

**Pull request merged**
